name: Increment Counter

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  increment-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Make script executable
        run: chmod +x increment_counter.sh

      - name: Run increment script
        run: ./increment_counter.sh

      - name: Push changes
        run: git push
